# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::SimpleCov; end
module ::SimpleCov; end
module ::SimpleCov::Formatter::HTMLFormatter; end
module ::SimpleCov::Formatter::MultiFormatter; end
